### ISSUE TITLE
mark.js is using 8.11.0 vs 8.11.1

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-menu#154] opened 2022-09-22 16:51 UTC
# General Support Request

Auro menu is using mark.js v 8.11.0 and we received an automated PR to update to 8.11.1 https://github.com/AlaskaAirlines/auro-menu/pull/153

The 8.11.1 update is failing to build. 

## Support request

Question: 8.11.1 was released 5 years ago, why did we use 8.11.0? 

Review and address the build error

```
TypeError: Cannot set properties of undefined (setting 'Mark')
```

**Comment by blackfalcon** [comment] 2022-09-22 16:53
148 files changed for a `patch` change, but ok https://github.com/julmot/mark.js/compare/8.11.0...8.11.1

**Comment by Patrick-Daly-AA** [comment] 2024-01-29 17:51
Duplicate of AlaskaAirlines/auro-form#40

**Closed as not planned by Patrick-Daly-AA** 2024-01-29 17:51 UTC
Labels: Type: Bug, auro-menu, not-reviewed
