### ISSUE TITLE
Citylist Dropdown Text Moves on Highlight

### ISSUE THREAD

**Issue by aesthetiques** [AlaskaAirlines/auro-menu#173] opened 2023-02-02 19:11 UTC
## Describe the bug

When selecting an option in the citylist dropdown, the padding on all options change

## To Reproduce

1. Go to ['Flight Search Microsite Search Form'](https://www.alaskaair.com/search)
2. Click into 'to' or 'from'
3. Type a city in
4. Notice the placement of the options, then use the arrow keys to navigate into the menu
5. All options will shift to the left

## Expected behavior

The options will not move when navigating into the options bib

## Screenshots
Before focusing the bib:
![image](https://user-images.githubusercontent.com/25255197/216427900-2131a589-7d47-4d6f-a46b-ffbb135c149d.png)
After:
![image](https://user-images.githubusercontent.com/25255197/216427978-09035a87-3f7b-4d12-9f9a-1d3560e76922.png)

## Desktop (please complete the following information):

 - OS: macOS
 - Browser Chrome 
 - Version 109.0.5414.119 (Official Build) (x86_64)

**Comment by jason-capsule42** [comment] 2023-02-02 20:43
Closing as a duplicate of #170

**Closed as completed by jason-capsule42** 2023-02-02 20:43 UTC
Labels: Type: Bug, not-reviewed
